### ISSUE TITLE
Bundling Types for a `.cts` File Doesn't Work in a Project With `type` set to `module`

### ISSUE THREAD

**Issue by manuth** [cometkim/nanobundle#108]
When trying to bundle a package with its entry point set to a `.cjs` file (originally sourced from a `.cts` file) in an ESM package, types aren't generated.

Source code is generated, however.

### Steps To Reproduce
  - Create a `package.json` file with its `type` property set to `module`
  - Create a `./src/index.cts` file
  - Create a `tsconfig.json` file with the following content:
    ```json
    {
        "compilerOptions": {
            "target": "ES6",
            "module": "Node16",
            "sourceMap": true,
            "sourceRoot": "./src",
            "outDir": "./lib"
        }
    }
    ```
  - Try to bundle the package:
    ```bash
    npx nanobundle build
    ```
  - Take note that only the `index.cjs` file is generated. The `index.d.cts` file is not.
  - Remove `"type": "module"` from your `package.json` and run the command again
  - Take note that the `d.cts` file is now generated

### Additional Info
It seems like the `sourceFile` array of the `types` entry is built incorrectly.
The `sourceFile` of the `types` entry contains the following paths:

```json
[
    "./src/index.d.cts",
    "./src/index.ts"
]
```

Where you'd actually expect something like this:

```js
[
    "./src/index.d.cts",
    "./src/index.cts",
    "./src/index.d.ts", // Maybe? idk
    "./src/index.ts" // Was already present in the original output - so why not leaving it in as well
]
```

<details>
<summary>

### Full Relevant Portion of the Debug Log

</summary>

```js
[debug] parsed entries [
  {
    key: 'main',
    entryPath: './lib/index.cjs',
    mode: undefined,
    minify: false,
    sourcemap: true,
    platform: 'neutral',
    module: 'commonjs',
    sourceFile: [
      './src/index.cts',
      './src/index.cjs',
      './src/index.ts',
      './src/index.js',
      [length]: 4
    ],
    outputFile: './lib/index.cjs',
    customConditions: [ [length]: 0 ]
  },
  {
    key: 'types',
    entryPath: './lib/index.d.cts',
    mode: undefined,
    minify: false,
    sourcemap: true,
    platform: 'neutral',
    module: 'dts',
    sourceFile: [
      './src/index.d.cts',
      './src/index.ts',
      [length]: 2
    ],
    outputFile: './lib/index.d.cts',
    customConditions: [ [length]: 0 ]
  },
  [length]: 2
]
```

</details>

**Comment by cometkim** [comment]
The fix has been released in v1.5.1
