### ISSUE TITLE
duplicate of tsconfck on the public npm registry

### ISSUE THREAD

**Issue by dominikg** [cometkim/nanobundle#219]
you published a duplicate of tsconfck to the public npm registry here https://www.npmjs.com/package/@nanobundle/tsconfck

possibly related to
https://github.com/cometkim/nanobundle/blob/558264786333ce4bdd6a6ac857bf560dd3eefb97/CHANGELOG.md?plain=1#L119

it still points to the original repo in the metadata though and it's not immediately clear what changes were made.

I would prefer you either take it down or update the metadata/readme so people don't get confused. 

If there was an issue for you in tsconfck, i'd be interested to hear about it and see if it is something that needs to be fixed in the original.

**Comment by cometkim** [comment]
Yes, that is a patch briefly used in a previous release and is no longer used. I will update and deprecate it soon.
