### ISSUE TITLE
Support for outputting bundles with JSX extensions

### ISSUE THREAD

**Issue by XiNiHa** [cometkim/nanobundle#76]
While Nanobundle respects `"jsx": "preserve"` in TSConfig and emits it as-is, I found that it doesn't accept JSX family extensions (`.jsx`, `.mjsx`, `.cjsx`) as output file extensions (instead it tries to look for something like `index.mjsx.js`, ...)
Outputting files with JSX extensions is important because Vite doesn't accept JSX when the extension is just plain `.js`. Transpiling the JSX when bundling isn't an option that I can consider. (since I'm currently building a library that exports a component for SolidJS)
Would it be possible to support outputting files with JSX extensions?

**Comment by cometkim** [comment]
This will be allowed in v1.1.0, but generally not recommended
