### ISSUE TITLE
How to generate only index.d.ts without bundle files?

### ISSUE THREAD

**Issue by easylogic** [cometkim/nanobundle#85]
How can I generator the index.d.ts file without a bundle file?

For example, 

```js
nanobundle build --generate-dts dist/index.d.ts 
```

**Comment by cometkim** [comment]
What is the use case? Is it instead of the dev command?

**Comment by easylogic** [comment]
It is possible with the typescript module. 
But I also want to do it with the nanobundle command

```sh
tsc -p ./tsconfig.json --watch --declaration --allowJs --emitDeclarationOnly
```

**Comment by cometkim** [comment]
You can use `--no-bundle` flag in v1.2.0, but probably better to wait #49
